### ISSUE TITLE
Enchacement: .env, config, multiple buttons (ban, dummy, approve)

### ISSUE THREAD

**Issue by sizeg** [mxssl/tg-captcha-bot#13]
I want to offer to add multiple buttons to prevent spam (buttons may be shuffle). I can do a PR, but it's better if u looking for my forked repository, cause i'm not a familiar with go yet (one day of research)

![photo_2020-01-27_18-55-21](https://user-images.githubusercontent.com/4047591/73200295-4cd24e80-4158-11ea-808c-3a9820fc79c2.jpg)

First one will ban a user at once, the second one is dummy, and the third one is to approve user.

Also to use .env to store bot token and use config.toml.example to get updates with out any problems.

**Comment by mxssl** [comment]
I think this goes beyond the main idea of the bot - to be as simple as possible. Your idea is really interesting but it will be better as a separate project/fork.
