### ISSUE TITLE
Show the name of the user who failed to pass

### ISSUE THREAD

**Issue by abitrolly** [mxssl/tg-captcha-bot#19]
![image](https://user-images.githubusercontent.com/8781107/143828801-e8bffb2c-3852-4304-a4b9-2ea5bd7be8e3.png)

It would be nice to know who was that.

**Comment by mxssl** [comment]
![tg](https://user-images.githubusercontent.com/14476356/143956982-9953395c-8a0d-4f3f-aa34-6f14a3b31696.JPG)

It is displayed as a reply to a "user joined the group" event.

**Comment by abitrolly** [comment]
![image](https://user-images.githubusercontent.com/8781107/144022934-43f05701-a988-4b6d-9002-ea4caceb7dbe.png)

Doesn't looks like channel saves these messages in history.
