### ISSUE TITLE
An example of captcha

### ISSUE THREAD

**Issue by abitrolly** [mxssl/tg-captcha-bot#20]
Need an example to see if users can pass it using alternative Telegram clients.

**Comment by mxssl** [comment]
All telegram clients that can use buttons feature are supported

https://core.telegram.org/api/bots/buttons

**Comment by abitrolly** [comment]
Is there a bot command to test my client?

**Comment by abitrolly** [comment]
I see there is no one. Will the PR be accepted to implement it?
