### ISSUE TITLE
уязвимость с разбаном

### ISSUE THREAD

**Issue by Viktor45** [mxssl/tg-captcha-bot#3]
когда кого то банят в чате в режим только чтение (например пользователю ограничены стикеры, написание сообщений, но он может читать группу), ему достаточно перевойти в чат, чтобы бот его разбанил в полный доступ через свой механизм, надо вам что-то поправить, чтобы если пользователь уже забанен в группе, чтобы бот его не трогал.

**Comment by r4rdsn** [comment]
#10 исправляет баг
