### ISSUE TITLE
Telegram Bot Token ["bot_token"] is incorrect. Token doesn't comply with regexp:

### ISSUE THREAD

**Issue by denisgolius** [mxssl/tg-captcha-bot#6]
tg-captcha-bot_1  | 2018/11/09 08:44:02 Telegram Bot Token ["503970099:AAE3AlrD_Y5uEXHKDCiifcttineD6-Esi6c"] is incorrect. Token doesn't comply with regexp: ^[0-9]+:.*$. Please, provide a correct Telegram Bot Token through env variable TGTOKEN

With other token, that is fresh generated - problem repeated.

**Comment by mxssl** [comment]
Solved
